const tasks = [
  {id:1,title:'월간 비용 리포트 생성',detail:'재무 데이터 집계 및 요약',agent:'Hermes',initial:'H',status:'running',label:'실행 중',progress:72,time:'10:42'},
  {id:2,title:'결제 API 회귀 테스트',detail:'checkout-service · 86개 케이스',agent:'Codex',initial:'CX',status:'running',label:'실행 중',progress:46,time:'10:38'},
  {id:3,title:'고객 문의 분류 및 초안',detail:'우선순위 높은 메일 18건',agent:'Claude Code',initial:'CC',status:'queued',label:'대기',progress:0,time:'10:35'},
  {id:4,title:'경쟁사 릴리스 노트 분석',detail:'주요 변경점과 영향도 정리',agent:'Gemini',initial:'G',status:'review',label:'검토 필요',progress:100,time:'10:21'},
  {id:5,title:'배포 파이프라인 최적화',detail:'캐시 계층 및 병렬 단계 점검',agent:'Codex',initial:'CX',status:'queued',label:'대기',progress:0,time:'10:16'},
  {id:6,title:'CRM 중복 레코드 정리',detail:'중복 후보 214건 병합',agent:'Hermes',initial:'H',status:'failed',label:'실패',progress:31,time:'09:58'}
];
const agents=[
  {name:'Hermes',initial:'H',meta:'오케스트레이터 · 4개 실행',availability:'정상',latency:'응답 0.8초'},
  {name:'Codex',initial:'CX',meta:'코드 실행기 · 3개 실행',availability:'정상',latency:'응답 1.4초'},
  {name:'Claude Code',initial:'CC',meta:'분석 실행기 · 2개 실행',availability:'정상',latency:'응답 1.1초'},
  {name:'Gemini',initial:'G',meta:'리서치 실행기 · 1개 실행',availability:'정상',latency:'응답 1.7초'}
];
const activities=[
  {icon:'✓',text:'월간 비용 리포트의 데이터 집계를 완료했습니다',meta:'Hermes · 작업 #HW-1842',time:'방금 전'},
  {icon:'↻',text:'결제 API 테스트가 40번째 케이스를 통과했습니다',meta:'Codex · checkout-service',time:'3분 전'},
  {icon:'＋',text:'고객 문의 분류 작업이 큐에 추가되었습니다',meta:'Hermes · 우선순위 높음',time:'7분 전'},
  {icon:'!',text:'CRM 정리 작업이 연결 시간 초과로 재시도됩니다',meta:'Hermes · 1/3회 재시도',time:'18분 전'}
];
const selected=new Set();
const queueBody=document.querySelector('#queueBody');
const statusFilter=document.querySelector('#statusFilter');
const agentFilter=document.querySelector('#agentFilter');
const searchInput=document.querySelector('#searchInput');

function toast(message){const region=document.querySelector('#toastRegion');const item=document.createElement('div');item.className='toast';item.innerHTML='<i>●</i><span></span>';item.querySelector('span').textContent=message;region.append(item);item.addEventListener('click',()=>item.remove());setTimeout(()=>item.remove(),3200)}
function visibleTasks(){const query=searchInput.value.trim().toLocaleLowerCase('ko');return tasks.filter(task=>(statusFilter.value==='all'||task.status===statusFilter.value)&&(agentFilter.value==='all'||task.agent===agentFilter.value)&&(!query||`${task.title} ${task.detail} ${task.agent}`.toLocaleLowerCase('ko').includes(query)))}
function renderTasks(){const rows=visibleTasks();queueBody.innerHTML=rows.map(task=>`<tr data-id="${task.id}" class="${selected.has(task.id)?'selected':''}"><td class="check"><input class="row-check" type="checkbox" aria-label="${task.title} 선택" ${selected.has(task.id)?'checked':''}></td><td><div class="task-title"><span class="task-icon">${String(task.id).padStart(2,'0')}</span><span><strong>${task.title}</strong><small>${task.detail}</small></span></div></td><td><div class="agent-cell"><span class="mini-avatar">${task.initial}</span>${task.agent}</div></td><td><span class="status ${task.status}"><i></i>${task.label}</span></td><td><div class="progress-cell"><div class="progress"><span style="width:${task.progress}%"></span></div><small>${task.progress}%</small></div></td><td class="right">${task.time}</td><td><button class="row-action" type="button" aria-label="${task.title} 작업 메뉴" data-row-action="${task.id}">⋯</button></td></tr>`).join('');document.querySelector('#emptyState').hidden=rows.length>0;document.querySelector('.table-wrap').hidden=rows.length===0;syncSelection();}
function syncSelection(){document.querySelector('#selectionBar').hidden=selected.size===0;document.querySelector('#selectionCount').textContent=`${selected.size}개 선택됨`;const visible=visibleTasks();const all=visible.length>0&&visible.every(t=>selected.has(t.id));const selectAll=document.querySelector('#selectAll');selectAll.checked=all;selectAll.indeterminate=!all&&visible.some(t=>selected.has(t.id));}
function resetFilters(){searchInput.value='';statusFilter.value='all';agentFilter.value='all';renderTasks()}
[statusFilter,agentFilter].forEach(el=>el.addEventListener('change',renderTasks));searchInput.addEventListener('input',renderTasks);document.querySelector('#clearFilters').addEventListener('click',resetFilters);document.querySelector('#emptyReset').addEventListener('click',resetFilters);
queueBody.addEventListener('change',e=>{if(!e.target.matches('.row-check'))return;const id=Number(e.target.closest('tr').dataset.id);e.target.checked?selected.add(id):selected.delete(id);renderTasks()});queueBody.addEventListener('click',e=>{const action=e.target.closest('[data-row-action]');if(action)toast(`${tasks.find(t=>t.id===Number(action.dataset.rowAction)).title} 메뉴를 열었습니다`)});
document.querySelector('#selectAll').addEventListener('change',e=>{visibleTasks().forEach(t=>e.target.checked?selected.add(t.id):selected.delete(t.id));renderTasks()});document.querySelector('#cancelSelected').addEventListener('click',()=>{selected.clear();renderTasks()});document.querySelector('#runSelected').addEventListener('click',()=>{toast(`${selected.size}개 작업을 실행 큐에 추가했습니다`);selected.clear();renderTasks()});
document.querySelectorAll('[data-toast]').forEach(el=>el.addEventListener('click',()=>toast(el.dataset.toast)));
document.querySelector('#refreshButton').addEventListener('click',e=>{e.currentTarget.firstElementChild.classList.add('spin');e.currentTarget.disabled=true;setTimeout(()=>{e.currentTarget.disabled=false;e.currentTarget.firstElementChild.classList.remove('spin');toast('최신 작업 상태로 동기화했습니다')},650)});
const root=document.documentElement;const themeToggle=document.querySelector('#themeToggle');function applyTheme(dark){root.classList.toggle('dark',dark);themeToggle.setAttribute('aria-label',dark?'라이트 테마로 전환':'다크 테마로 전환');localStorage.setItem('hermes-theme',dark?'dark':'light')}const saved=localStorage.getItem('hermes-theme');applyTheme(saved?saved==='dark':matchMedia('(prefers-color-scheme: dark)').matches);themeToggle.addEventListener('click',()=>applyTheme(!root.classList.contains('dark')));
const sidebar=document.querySelector('#sidebar');const backdrop=document.querySelector('#sidebarBackdrop');const menuButton=document.querySelector('#menuButton');function mobileMenu(open){sidebar.classList.toggle('mobile-open',open);backdrop.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'사이드바 닫기':'사이드바 열기')}menuButton.addEventListener('click',()=>mobileMenu(!sidebar.classList.contains('mobile-open')));backdrop.addEventListener('click',()=>mobileMenu(false));document.querySelector('#collapseButton').addEventListener('click',()=>document.querySelector('.app-shell').classList.toggle('collapsed'));document.addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='b'){e.preventDefault();document.querySelector('.app-shell').classList.toggle('collapsed')}if(e.key==='Escape')mobileMenu(false)});
document.querySelector('#agentList').innerHTML=agents.map(a=>`<div class="agent-row"><span class="avatar">${a.initial}</span><span><strong>${a.name}</strong><small>${a.meta}</small></span><span class="availability"><b><span class="status running"><i></i>${a.availability}</span></b><span>${a.latency}</span></span></div>`).join('');document.querySelector('#timeline').innerHTML=activities.map(a=>`<li><span class="timeline-icon">${a.icon}</span><span><p>${a.text}</p><small>${a.meta}</small></span><time>${a.time}</time></li>`).join('');
function renderChart(){const svg=document.querySelector('#workloadChart');const data=[{d:'8/16',ok:28,fail:2},{d:'8/17',ok:34,fail:1},{d:'8/18',ok:31,fail:3},{d:'8/19',ok:46,fail:2},{d:'8/20',ok:39,fail:4},{d:'8/21',ok:51,fail:1},{d:'오늘',ok:43,fail:1}];const max=60;let markup='';[0,20,40,60].forEach(v=>{const y=202-v/max*172;markup+=`<line class="chart-grid" x1="44" x2="704" y1="${y}" y2="${y}"/><text class="chart-label" x="34" y="${y+4}" text-anchor="end">${v}</text>`});data.forEach((v,i)=>{const x=64+i*92;const okH=v.ok/max*172,failH=v.fail/max*172;markup+=`<rect class="bar-done" x="${x}" y="${202-okH}" width="24" height="${okH}" rx="4"/><rect class="bar-fail" x="${x+28}" y="${202-failH}" width="10" height="${failH}" rx="3"/><text class="chart-label" x="${x+18}" y="226" text-anchor="middle">${v.d}</text>`});svg.innerHTML='<desc id="chart-desc">8월 16일부터 22일까지 완료와 실패 작업량 막대 차트</desc>'+markup}renderChart();renderTasks();
