const products=[
  {id:1,title:'매트 진공 보온 텀블러',detail:'500ml · 모스 그린 · 1개입',source:'taobao / 891899395011',images:19,status:'review',label:'검수 필요',stage:'사실 검수',progress:38,time:'방금 전'},
  {id:2,title:'접이식 캠핑 수납 박스',detail:'45L · 샌드 베이지 · 뚜껑 포함',source:'taobao / 912845316722',images:24,status:'running',label:'생성 중',stage:'9컷 생성',progress:56,time:'3분 전'},
  {id:3,title:'무선 LED 무드등',detail:'USB-C · 웜 화이트 · 3단 밝기',source:'taobao / 827049183065',images:15,status:'capture',label:'원본 수집',stage:'원본 분류',progress:18,time:'11분 전'},
  {id:4,title:'실리콘 이유식 흡착 식판',detail:'그레이 · 4칸 · 스푼 포함',source:'taobao / 813920447501',images:21,status:'ready',label:'검수 대기',stage:'최종 검수',progress:100,time:'22분 전'},
  {id:5,title:'우드 데스크 케이블 트레이',detail:'월넛 · 60cm · 클립 6개',source:'taobao / 900831364291',images:13,status:'queued',label:'대기',stage:'판매 전략',progress:12,time:'36분 전'},
  {id:6,title:'반려동물 휴대용 물통',detail:'300ml · 라이트 블루 · 필터 포함',source:'taobao / 790312885417',images:17,status:'review',label:'검수 필요',stage:'사실 검수',progress:38,time:'48분 전'},
  {id:7,title:'린넨 주방 앞치마',detail:'내추럴 · 프리사이즈 · 포켓 2개',source:'taobao / 883715204622',images:12,status:'ready',label:'검수 대기',stage:'최종 검수',progress:100,time:'1시간 전'}
];
const cutNames=['메인 비주얼','구매 이유','핵심 소재','사용 장면','제품 디테일','옵션 안내','사용 방법','사이즈 안내','구매 유도'];
const selected=new Set();let activeId=1;let factChecked=false;let generated=0;let generationTimer=null;
const queueBody=document.querySelector('#queueBody');const searchInput=document.querySelector('#searchInput');const statusFilter=document.querySelector('#statusFilter');
function toast(message){const region=document.querySelector('#toastRegion');const item=document.createElement('div');item.className='toast';item.innerHTML='<i>●</i><span></span>';item.querySelector('span').textContent=message;region.append(item);setTimeout(()=>item.remove(),3200)}
function activeProduct(){return products.find(product=>product.id===activeId)}
function visibleProducts(){const q=searchInput.value.trim().toLocaleLowerCase('ko');return products.filter(product=>(statusFilter.value==='all'||product.status===statusFilter.value)&&(!q||`${product.title} ${product.detail} ${product.source}`.toLocaleLowerCase('ko').includes(q)))}
function renderQueue(){const rows=visibleProducts();queueBody.innerHTML=rows.map(product=>`<tr data-id="${product.id}" class="${activeId===product.id?'selected':''}"><td class="check"><input class="row-check" type="checkbox" aria-label="${product.title} 선택" ${selected.has(product.id)?'checked':''}></td><td><button class="task-title task-select" data-select="${product.id}" type="button"><span class="task-icon">${String(product.id).padStart(2,'0')}</span><span><strong>${product.title}</strong><small>${product.detail}</small></span></button></td><td class="source-cell">이미지 ${product.images}개<br>${product.source.split('/ ')[1]}</td><td>${product.stage}</td><td><span class="status ${product.status}"><i></i>${product.label}</span></td><td><div class="progress-cell"><div class="progress"><span style="width:${product.progress}%"></span></div><small>${product.progress}%</small></div></td><td class="right">${product.time}</td><td><button class="row-action" type="button" data-more="${product.id}" aria-label="${product.title} 작업 메뉴">⋯</button></td></tr>`).join('');document.querySelector('#emptyState').hidden=rows.length>0;document.querySelector('.table-wrap').hidden=rows.length===0;document.querySelector('#queueCount').textContent=products.length;syncSelection()}
function syncSelection(){const list=visibleProducts();const all=list.length>0&&list.every(item=>selected.has(item.id));const checkbox=document.querySelector('#selectAll');checkbox.checked=all;checkbox.indeterminate=!all&&list.some(item=>selected.has(item.id));document.querySelector('#selectionBar').hidden=selected.size===0;document.querySelector('#selectionCount').textContent=`${selected.size}개 선택됨`}
function resetFilters(){searchInput.value='';statusFilter.value='all';renderQueue()}
function renderSelected(){const product=activeProduct();document.querySelector('#selectedTitle').textContent=product.title;document.querySelector('#selectedSource').textContent=`${product.source} · 원본 이미지 ${product.images}개`;document.querySelector('#selectedMeta').textContent=`${product.stage} 단계입니다. 원본을 확인하고 필수 사실을 검수한 뒤 생성할 수 있습니다.`;const chip=document.querySelector('#selectedStatus');chip.className=`status ${factChecked?'running':product.status}`;chip.innerHTML=`<i></i>${factChecked?'생성 준비':'검수 필요'}`;document.querySelector('#factToggle').classList.toggle('checked',factChecked);document.querySelector('#factCount').className=`badge ${factChecked?'success':'warning'}`;document.querySelector('#factCount').textContent=factChecked?'3 / 3 확인':'2 / 3 확인';document.querySelector('#runButton').disabled=!factChecked||generated>0;document.querySelector('#gateHint').textContent=factChecked?'필수 검수가 완료되었습니다. 9개의 상세 컷 생성을 시작할 수 있습니다.':'소재·용량·구성품을 확인하면 9컷 생성 단계를 시작할 수 있습니다.'}
function renderCuts(){const grid=document.querySelector('#cutGrid');grid.innerHTML=cutNames.map((name,index)=>{const number=index+1;const type=number<=generated?'ready':number===generated+1&&generationTimer?'generating':'pending';return `<button class="cut ${type}" type="button" ${type==='pending'?'disabled':''} data-cut="${number}"><span class="cut-number">${String(number).padStart(2,'0')}</span><span class="cut-art"></span><span class="cut-name">${name}</span></button>`}).join('');document.querySelector('#cutProgress').textContent=`${generated} / 9`;document.querySelector('#generationProgress').style.width=`${generated/9*100}%`;document.querySelector('#generationLabel').textContent=generated===9?'9개 컷 생성 완료':generationTimer?`${generated}번째 컷 생성 중`:'생성 전';document.querySelector('#assetSubtitle').textContent=generated===9?'전체 9컷이 준비되었습니다. 상세페이지 조립 전 최종 흐름을 검수하세요.':factChecked?'데모 생성은 대표 상품의 세로형 컷 순서를 보여줍니다.':'검수 완료 후 9개의 세로 컷을 순서대로 생성합니다.';document.querySelector('#previewButton').disabled=generated<9}
const activities=[
  {icon:'✓',text:'무선 LED 무드등 원본 이미지 15개를 분류했습니다',meta:'collector-v2 · taobao / 827049183065',time:'11분 전'},
  {icon:'↻',text:'접이식 캠핑 수납 박스의 5번째 상세 컷을 생성했습니다',meta:'detail-pages · 5 / 9 cuts',time:'3분 전'},
  {icon:'!',text:'매트 진공 보온 텀블러의 소재·용량 확인이 필요합니다',meta:'gate-facts · 판매자 검수 대기',time:'방금 전'},
  {icon:'＋',text:'린넨 주방 앞치마를 최종 검수 큐에 추가했습니다',meta:'compose-detail · 9 cuts complete',time:'1시간 전'}
];
function renderActivity(){document.querySelector('#timeline').innerHTML=activities.slice(0,5).map(item=>`<li><span class="timeline-icon">${item.icon}</span><span><p>${item.text}</p><small>${item.meta}</small></span><time>${item.time}</time></li>`).join('')}
function activateProduct(id){activeId=id;factChecked=false;generated=0;clearInterval(generationTimer);generationTimer=null;renderQueue();renderSelected();renderCuts();document.querySelector('#workflow').scrollIntoView({behavior:'smooth',block:'start'});toast(`${activeProduct().title} 작업을 열었습니다`)}
function addActivity(icon,text,meta){activities.unshift({icon,text,meta,time:'방금 전'});renderActivity()}
queueBody.addEventListener('click',event=>{const choose=event.target.closest('[data-select]');const more=event.target.closest('[data-more]');if(choose)activateProduct(Number(choose.dataset.select));if(more)toast(`${products.find(item=>item.id===Number(more.dataset.more)).title} 메뉴를 열었습니다`)});
queueBody.addEventListener('change',event=>{if(!event.target.matches('.row-check'))return;const id=Number(event.target.closest('tr').dataset.id);event.target.checked?selected.add(id):selected.delete(id);renderQueue()});
document.querySelector('#selectAll').addEventListener('change',event=>{visibleProducts().forEach(item=>event.target.checked?selected.add(item.id):selected.delete(item.id));renderQueue()});
searchInput.addEventListener('input',renderQueue);statusFilter.addEventListener('change',renderQueue);document.querySelector('#clearFilters').addEventListener('click',resetFilters);document.querySelector('#emptyReset').addEventListener('click',resetFilters);document.querySelector('#showAll').addEventListener('click',resetFilters);document.querySelector('#cancelSelected').addEventListener('click',()=>{selected.clear();renderQueue()});document.querySelector('#runSelected').addEventListener('click',()=>{const first=[...selected][0];selected.clear();activateProduct(first)});
document.querySelector('#factToggle').addEventListener('click',()=>{factChecked=!factChecked;renderSelected();renderCuts();toast(factChecked?'필수 검수가 완료되었습니다. 9컷 생성을 시작할 수 있습니다.':'필수 검수 상태를 되돌렸습니다.')});
document.querySelector('#facts').addEventListener('click',event=>{if(event.target.closest('.locked'))toast('이 항목은 원본 분류 또는 안전 기준으로 자동 적용됩니다.')});
document.querySelector('#runButton').addEventListener('click',()=>{if(!factChecked||generationTimer)return;generationTimer=setInterval(()=>{generated+=1;renderCuts();addActivity('✦',`${activeProduct().title} · ${generated}번 ${cutNames[generated-1]} 컷을 생성했습니다`,'detail-pages · 제품 형태 참조 유지');if(generated>=9){clearInterval(generationTimer);generationTimer=null;renderCuts();renderSelected();addActivity('✓',`${activeProduct().title} 상세 컷 9개 생성이 완료되었습니다`,'compose-detail · 최종 검수로 이동 가능');toast('9개 컷 생성이 완료되었습니다. 전체 미리보기를 열어보세요.') }},480);renderCuts();toast('데모 생성 작업을 시작했습니다.')});
document.querySelector('#cutGrid').addEventListener('click',event=>{const cut=event.target.closest('[data-cut]');if(cut)toast(`${cut.dataset.cut}번 ${cutNames[Number(cut.dataset.cut)-1]} 컷 미리보기입니다. 실제 이미지 생성은 아직 연결되지 않았습니다.`)});document.querySelector('#previewButton').addEventListener('click',()=>toast('전체 9컷 미리보기는 다음 실제 상세페이지 조립 단계에서 연결합니다.'));document.querySelector('#sourceButton').addEventListener('click',()=>toast(`원본 이미지 ${activeProduct().images}개를 확인하는 화면은 아직 연결되지 않았습니다.`));
document.querySelector('#newTaskButton').addEventListener('click',()=>toast('새 제작 접수 화면은 실제 상품 수집 연결 후 열립니다.'));document.querySelectorAll('[data-toast]').forEach(element=>element.addEventListener('click',()=>toast(element.dataset.toast)));document.querySelector('#clearActivity').addEventListener('click',()=>toast('최근 활동을 모두 확인했습니다.'));
document.querySelector('#refreshButton').addEventListener('click',event=>{event.currentTarget.disabled=true;event.currentTarget.firstElementChild.textContent='↻';setTimeout(()=>{event.currentTarget.disabled=false;toast('데모 제작 큐를 최신 상태로 동기화했습니다.')},500)});
const root=document.documentElement;const themeToggle=document.querySelector('#themeToggle');function applyTheme(dark){root.classList.toggle('dark',dark);themeToggle.setAttribute('aria-label',dark?'라이트 테마로 전환':'다크 테마로 전환');localStorage.setItem('detailflow-theme',dark?'dark':'light')}applyTheme(localStorage.getItem('detailflow-theme')==='dark');themeToggle.addEventListener('click',()=>applyTheme(!root.classList.contains('dark')));
const sidebar=document.querySelector('#sidebar');const backdrop=document.querySelector('#sidebarBackdrop');const menuButton=document.querySelector('#menuButton');function mobileMenu(open){sidebar.classList.toggle('mobile-open',open);backdrop.hidden=!open;menuButton.setAttribute('aria-expanded',String(open));menuButton.setAttribute('aria-label',open?'사이드바 닫기':'사이드바 열기')}menuButton.addEventListener('click',()=>mobileMenu(!sidebar.classList.contains('mobile-open')));backdrop.addEventListener('click',()=>mobileMenu(false));document.querySelector('#collapseButton').addEventListener('click',()=>document.querySelector('.app-shell').classList.toggle('collapsed'));document.addEventListener('keydown',event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==='b'){event.preventDefault();document.querySelector('.app-shell').classList.toggle('collapsed')}if(event.key==='Escape')mobileMenu(false)});
document.querySelector('#draftThreadButton').addEventListener('click',()=>{const topic=document.querySelector('#threadTopic').value.trim();if(!topic){toast('Threads 초안을 만들 주제를 입력하세요.');return}const items=document.querySelector('#threadItems');const item=document.createElement('button');item.className='thread-item active';item.type='button';item.innerHTML=`<span class="thread-dot ready"></span><span><b>${topic}</b><small>5포스트 초안 · 검수 대기</small></span><em>방금 전</em>`;items.prepend(item);document.querySelectorAll('.thread-item').forEach((node,index)=>node.classList.toggle('active',index===0));document.querySelector('#threadCount').textContent=`${items.children.length}건`;const steps=document.querySelectorAll('#threadSteps li');steps[1].className='done';steps[1].querySelector('small').textContent='완료';steps[2].className='active';steps[2].querySelector('small').textContent='검수 대기';addActivity('✦',`Threads 5포스트 초안을 생성했습니다: ${topic}`,'threads-draft · 대시보드 시뮬레이션');toast('Threads 5포스트 초안을 콘텐츠 큐에 추가했습니다. 실제 게시·예약은 연결하지 않았습니다.')});
document.querySelector('#threadItems').addEventListener('click',event=>{const item=event.target.closest('.thread-item');if(!item)return;document.querySelectorAll('.thread-item').forEach(node=>node.classList.toggle('active',node===item));toast('Threads 콘텐츠 초안을 선택했습니다.')});
renderQueue();renderSelected();renderCuts();renderActivity();
